# Change these first
owner: ischaojie # Your GitHub organization or username, where this repository lives
repo: doup # The name of this repository

sites:
  - name: Douban
    url: https://www.douban.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
